// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollBot.Data;

#nullable disable

namespace PollBot.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240707154636_AddChatTitle")]
    partial class AddChatTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("PollBot.Data.Models.ChatPoll", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastPollId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPollTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PollName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PollOptions")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("ChatPolls");
                });
#pragma warning restore 612, 618
        }
    }
}
