// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollBot.Data;

#nullable disable

namespace PollBot.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("PollBot.Data.Models.ChatPoll", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastPollId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPollTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("ChatPolls");
                });
#pragma warning restore 612, 618
        }
    }
}
